apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sre-challenge-app
  namespace: sre-challenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sre-challenge-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
