apiVersion: v1
kind: Service
metadata:
  name: sre-challenge-app
  namespace: sre-challenge
  labels:
    app: sre-challenge-app
spec:
  type: NodePort
  selector:
    app: sre-challenge-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000 # Porta externa para acesso
