apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-access
  namespace: sre-challenge
spec:
  podSelector:
    matchLabels:
      app: sre-challenge-app
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: db
    ports:
    - protocol: TCP
      port: 3306