kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: sre-challenge
  name: sre-challenge-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: sre-challenge
  name: sre-challenge-rolebinding
subjects:
- kind: User
  name: team-a-user # Identidade do usuário da equipe
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sre-challenge-role
  apiGroup: rbac.authorization.k8s.io
